### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 2)

### ISSUE THREAD

**Issue by pele88** [JonathanHolvey/sharepy#30]
Effectively trying to load an .xlsx file on Sharepoint into a pandas dataframe but I can't seem to be able to get the json() out properly. Are there any additional headers I need to be passing in? Or how would you suggest to decode this properly?

Thanks.

```
>>> import sharepy
>>> s = sharepy.connect('mysite.sharepoint.com', username=username, password=password)
Requesting security token...
Requesting access cookie... 
Authentication successful   

>>> response = s.get('https://mysite.sharepoint.com/sites/SiteDir/_layouts/15/Doc.aspx?OR=teams&action=edit&sourcedoc={99E8E198-999C-99E9-93D3-9972990AE2D6}')

>>> response.headers
{'Cache-Control': 'no-cache, no-store', 'Pragma': 'no-cache', 'Content-Length': '23637', 'Content-Type': 'text/html; charset=utf-8', 'Content-Encoding': 'gzip', 'Expires': '-1', 'Vary': 'Accept-Encoding', ......

>>> response.json()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 2)
```

**Comment by JonathanHolvey** [comment]
It looks like the data you're trying to load from the isn't formatted as JSON. The fact it is an XLSX file (which is an XML-based format) pretty much confirms this. Try using `response.text` instead to see the raw response data.

Pandas should be able to read that string directly:
```python
import pandas as pd
pd.read_excel(response.text)
```

**Comment by pele88** [comment]
Good point, however actually looks like it's returning an HTML type:

```
>>> response.text
'\r\n<!DOCTYPE html>\r\n<html>\r\n\r\n<head>\r\n\t<meta http-equiv="X-UA-Compatible" content="IE=edge" />\r\n\t<meta name=\'vi

>>> pd.read_html(response.text)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/pandas/io/html.py", line 1094, in read_html
    displayed_only=displayed_only)
  File "/usr/local/lib/python3.6/site-packages/pandas/io/html.py", line 916, in _parse
    raise_with_traceback(retained)
  File "/usr/local/lib/python3.6/site-packages/pandas/compat/__init__.py", line 420, in raise_with_traceback
    raise exc.with_traceback(traceback)
ValueError: No tables found
```

Alternatively, using `read_excel`:

```
>>> df = pd.read_excel(response.text)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/pandas/util/_decorators.py", line 188, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pandas/util/_decorators.py", line 188, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pandas/io/excel.py", line 350, in read_excel
    io = ExcelFile(io, engine=engine)
  File "/usr/local/lib/python3.6/site-packages/pandas/io/excel.py", line 653, in __init__
    self._reader = self._engines[engine](self._io)
  File "/usr/local/lib/python3.6/site-packages/pandas/io/excel.py", line 424, in __init__
    self.book = xlrd.open_workbook(filepath_or_buffer)
  File "/usr/local/lib/python3.6/site-packages/xlrd/__init__.py", line 116, in open_workbook
    with open(filename, "rb") as f:
OSError: [Errno 63] File name too long: '\r\n<!DOCTYPE html>\r\n<html>\r\n\r\n<head>\r\n\t<meta http-equiv="X-UA-Compatible"
```

Thanks.

**Comment by JonathanHolvey** [comment]
Yes, that certainly looks like HTML. If you check the entire document you might find it's an error page, telling you why you can't access the file you're after.

**Comment by pele88** [comment]
Loaded the HTML in my browser to find a blank screen of new line characters. No error message.

`getfile` works fine to local storage.

**Comment by bakliwal123** [comment]
I am getting HTML content in response while doing r.content.
When i tried `pd.read_excel(response.text)` I am getting Unicode Encode Error.
Need suggestions

**Comment by JonathanHolvey** [comment]
Have you verified that your response actually contains an Excel file? If, as you suggest the response contains HTML, you won't be able to read it as an Excel file.

Take a look at the response data to work out what's going wrong.

**Comment by bakliwal123** [comment]
@JonathanHolvey Thanks for the response, yeah I am not able to do response.text even instead i checked with response.content.Here I found it is in HTML. Dont understand how to proceed further, as the repsonse itself in HTML.

**Comment by bakliwal123** [comment]
@JonathanHolvey

 Sorry to bother you again

I am working on another way,this time i found the url from where we can download .iqy file from sharepoint directly.Below url is giving 200 response code.

`https://<siteurl>/_vti_bin/owssvr.dll?CS=109&Using=_layouts/query.iqy&List={<List GUID>}&View={<List View GUID>}&CacheControl=1` 

I am just wondering how i can use this in python scipt to read  the file and create xls/csv file to disered location.
