### ISSUE TITLE
sharepy.errors.AuthError: 'Unknown' namespace sites are not supported

### ISSUE THREAD

**Issue by somasud** [JonathanHolvey/sharepy#81]
When I tried to connect to SharePoint using sharepy==2.0.0, I get this following error.

$ ../../../Program\ Files/Python310/python.exe copySkillMatrixFiles.py
Trying to connect to Sharepoint with XXXXXX and XXXXXXX
Authenticating ....
Traceback (most recent call last):
    s = sharepy.connect("https://admiralgroupplc.sharepoint.com/teams/Engineering/", username=username, password=password)
  File "C:\Users\somasud\AppData\Roaming\Python\Python310\site-packages\sharepy\session.py", line 14, in connect
    autoauth = auth.detect(username=username, password=password)
  File "C:\Users\somasud\AppData\Roaming\Python\Python310\site-packages\sharepy\auth\detect.py", line 31, in detect
    raise errors.AuthError(f'\'{auth_type}\' namespace sites are not supported')
sharepy.errors.AuthError: 'Unknown' namespace sites are not supported

Can someone please help? How do I know the supported namespace? what does it mean by namespace sites not supported?

**Comment by somasud** [comment]
This is a Microsoft 365 SharePoint site used by my organisation

**Comment by A-wels** [comment]
Did you add '@youdomain.xyz' to the end of the username? Try seraching for the user and using the complete username with this part included.

**Comment by Jamie-** [comment]
This looks like you may need these changes I think https://github.com/JonathanHolvey/sharepy/pull/76
