### ISSUE TITLE
Pyinstaller: saml-template.xml file not found

### ISSUE THREAD

**Issue by CQzhangjiawang** [JonathanHolvey/sharepy#82]
Thank you very much to the author for giving me a great help.
I have a question that I want to ask you about me.Please help me.

It worked very well when I wrote the code, but after I packaged it with pyinstaller, I couldn't find the `saml-template.xml` file. Is there any way to find the `saml-template.xml` file? Or How can I set the the xml path?
`
Please input any key to exit...Traceback (most recent call last):
  File "spo.py", line 56, in main
    tool = SPOTool(site_url=config['site_url'], user_name=config['user_name'], password=config['password'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "spo_tool.py", line 32, in __init__
    self.request = sharepy.connect(site_url, username=user_name, password=password)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "sharepy\session.py", line 20, in connect
  File "sharepy\session.py", line 61, in __init__
  File "sharepy\session.py", line 71, in _spauth
**FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\CQCB76~1.ZHA\\AppData\\Local\\Temp\\_MEI194762\\sharepy\\saml-template.xml'**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "spo.py", line 221, in <module>
    main()
  File "spo.py", line 61, in main
    raise Exception(f"403: Auth failed! Please check the following keys in config json file: {required_keys}")
Exception: 403: Auth failed! Please check the following keys in config json file: ['site_url', 'user_name', 'password']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "spo.py", line 224, in <module>
    input("Please input any key to exit...")
KeyboardInterrupt
[PYI-22288:ERROR] Failed to execute script 'spo' due to unhandled exception!
`

**Comment by CQzhangjiawang** [comment]
Rresolved by the following command:
`pyinstaller --add-data "/path/to/saml-template.xml;sharepy" -F xxx.py`
